sonar.projectKey=firstsun-dev_watermark-s3-uploader
sonar.organization=firstsun-dev

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=watermark-s3-uploader
sonar.projectVersion=1.1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**, dist/**, main.js, styles.css, manifest.json

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Test coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
