name: CI/CD

on:
  push:
    branches: [main, master, '**']
  pull_request:

jobs:
  workflow-call:
    uses: firstsun-dev/general-workflows/.github/workflows/plugin-ci.yml@84bf7e14a29b9cc767066b7d038219af485c5716
    with:
      plugin-id: "watermark-s3-uploader"
